import type { IpcCommandMap } from '@/lib/types/ipc'

export const fixtures: {
  [CommandName in keyof IpcCommandMap]: IpcCommandMap[CommandName]['response']
} = {
  get_initial_shell: {
    panes: [
      {
        id: 'left',
        title: 'Left pane',
        path: 'C:\\Users\\Omega',
        placeholderHeading: '',
        placeholderBody: '',
      },
      {
        id: 'right',
        title: 'Right pane',
        path: 'D:\\projects',
        placeholderHeading: '',
        placeholderBody: '',
      },
    ],
    treeRoots: [
      { id: 'this-pc', label: 'This PC' },
      { id: 'projects', label: 'Projects' },
    ],
  },
  list_dir: {
    path: 'C:\\Users\\Omega',
    entries: [
      {
        id: 'docs',
        name: 'Documents',
        path: 'C:\\Users\\Omega\\Documents',
        isDir: true,
        sizeBytes: null,
        itemCount: 12,
        typeLabel: 'Folder',
        modifiedAt: '2026-06-20T10:15:00Z',
        createdAt: '2026-06-01T10:15:00Z',
        attributes: [],
        isHidden: false,
        isSystem: false,
      },
      {
        id: 'media',
        name: 'Media',
        path: 'C:\\Users\\Omega\\Media',
        isDir: true,
        sizeBytes: null,
        itemCount: 8,
        typeLabel: 'Folder',
        modifiedAt: '2026-06-21T10:15:00Z',
        createdAt: '2026-05-01T10:15:00Z',
        attributes: [],
        isHidden: false,
        isSystem: false,
      },
      {
        id: 'report',
        name: 'Report.txt',
        path: 'C:\\Users\\Omega\\Report.txt',
        isDir: false,
        sizeBytes: 2048,
        itemCount: null,
        typeLabel: 'TXT file',
        modifiedAt: '2026-06-22T10:15:00Z',
        createdAt: '2026-06-10T10:15:00Z',
        attributes: [],
        isHidden: false,
        isSystem: false,
      },
    ],
  },
  create_folder: {
    id: 'C:\\Users\\Omega\\New folder',
    name: 'New folder',
    path: 'C:\\Users\\Omega\\New folder',
    isDir: true,
    sizeBytes: null,
    itemCount: 0,
    typeLabel: 'Folder',
    modifiedAt: '2026-06-24T10:15:00Z',
    createdAt: '2026-06-24T10:15:00Z',
    attributes: [],
    isHidden: false,
    isSystem: false,
  },
  create_file: {
    id: 'C:\\Users\\Omega\\New file.txt',
    name: 'New file.txt',
    path: 'C:\\Users\\Omega\\New file.txt',
    isDir: false,
    sizeBytes: 0,
    itemCount: null,
    typeLabel: 'TXT file',
    modifiedAt: '2026-06-24T10:15:00Z',
    createdAt: '2026-06-24T10:15:00Z',
    attributes: [],
    isHidden: false,
    isSystem: false,
  },
  rename_entry: {
    id: 'C:\\Users\\Omega\\Renamed',
    name: 'Renamed',
    path: 'C:\\Users\\Omega\\Renamed',
    isDir: true,
    sizeBytes: null,
    itemCount: 0,
    typeLabel: 'Folder',
    modifiedAt: '2026-06-24T10:15:00Z',
    createdAt: '2026-06-24T10:15:00Z',
    attributes: [],
    isHidden: false,
    isSystem: false,
  },
  delete_entries: undefined,
  open_path: undefined,
  list_volumes: [
    {
      mountRoot: 'Z:\\',
      label: 'Share',
      totalBytes: 500_000_000,
      freeBytes: 200_000_000,
      isNetwork: true,
    },
    {
      mountRoot: 'C:\\',
      label: 'Windows',
      totalBytes: 1_000_000_000,
      freeBytes: 500_000_000,
      isNetwork: false,
    },
    {
      mountRoot: 'D:\\',
      label: 'Projects',
      totalBytes: 2_000_000_000,
      freeBytes: 1_400_000_000,
      isNetwork: false,
    },
  ],
  everything_status: {
    status: 'available',
    isAvailable: true,
  },
  request_folder_size: undefined,
  request_folder_sizes: undefined,
  cancel_size: {
    cancelled: false,
  },
  set_tab_watch: undefined,
  refresh_tab: {
    tabId: 'left-1',
    path: 'C:\\Users\\Omega',
    reason: 'refresh',
    changed: [],
    removed: [],
  },
  load_config: {
    theme: 'dark',
    showHiddenFiles: false,
    dismissedEverythingBanner: false,
    keybindings: {},
    columns: [
      { key: 'name', visible: true },
      { key: 'size', visible: true },
      { key: 'items', visible: true },
      { key: 'type', visible: true },
      { key: 'modified', visible: true },
      { key: 'created', visible: false },
    ],
    layout: {
      detailsVisible: false,
      treeWidth: 'default',
      defaultPaneMode: 'dual',
      restoreSession: true,
    },
  },
  save_config: {
    theme: 'dark',
    showHiddenFiles: false,
    dismissedEverythingBanner: false,
    keybindings: {},
    columns: [
      { key: 'name', visible: true },
      { key: 'size', visible: true },
      { key: 'items', visible: true },
      { key: 'type', visible: true },
      { key: 'modified', visible: true },
      { key: 'created', visible: false },
    ],
    layout: {
      detailsVisible: false,
      treeWidth: 'default',
      defaultPaneMode: 'dual',
      restoreSession: true,
    },
  },
  load_session: {
    activePane: 'left',
    leftPath: 'C:\\Users\\Omega',
    rightPath: 'D:\\projects',
  },
  save_session: {
    activePane: 'left',
    leftPath: 'C:\\Users\\Omega',
    rightPath: 'D:\\projects',
  },
  start_op: 'op-1',
  pause_op: undefined,
  resume_op: undefined,
  cancel_op: undefined,
  retry_op: undefined,
  reorder_ops: undefined,
  resolve_conflict: undefined,
  queue_snapshot: [],
  has_unfinished_ops: false,
  log_frontend: undefined,
}
