[alias]
gm-test-integration = "nextest run --manifest-path src-tauri/Cargo.toml --features test-utils --test integration"
gm-llvm-cov = "llvm-cov nextest --no-clean --manifest-path src-tauri/Cargo.toml --features test-utils --test integration --fail-under-lines 90 --fail-under-functions 90 --fail-under-regions 80"
